exclude_patterns:
  - "**/__mocks__/"
  - "**/constants/"
  - "**/node_modules/"
  - "**/*.test.ts"
  - "packages/*/*/test/"
checks:
  file-lines:
    config:
      threshold: 50
  similar-code:
    enabled: false
