name: Continues Integration
on: push
jobs:
  release:
    name: Continues Integration
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Turbo
        run: npm install -g turbo
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: turbo run build
      - name: Lint
        run: turbo run lint
      - name: Unit Tests
        run: turbo run test
      - name: Integration Tests
        run: turbo run test:scenarios
      - name: Coverage Report
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: |
            ${{github.workspace}}/packages/runtime/*/coverage/lcov.info:lcov
